<?php

/**
 * @file
 * Contains podcasts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function podcasts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the podcasts module.
    case 'help.page.podcasts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Milken Podcast Integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function podcasts_theme() {
  return [
    'podcasts' => [
      'render element' => 'children',
    ],
  ];
}
